# Generated by Django 4.0.1 on 2022-01-16 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolygo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('tipus', models.CharField(blank=True, max_length=40)),
                ('pontertek', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoJegyben2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('adatok', models.JSONField(blank=True, default=dict)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Haz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('tipus', models.CharField(blank=True, max_length=50)),
                ('mundan_jegye', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazJegyben2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jegy2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('elem', models.CharField(blank=True, max_length=20)),
                ('minoseg', models.CharField(blank=True, max_length=20)),
                ('paritas', models.CharField(blank=True, max_length=20)),
                ('evszak', models.CharField(blank=True, max_length=20)),
                ('uralkodo_bolygo', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic2')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created2', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Horoszkop2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonos_neve', models.CharField(max_length=30)),
                ('idopont', models.DateTimeField(default=datetime.datetime(2022, 1, 16, 23, 0, 26, 411063))),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('kepletkep', models.ImageField(default='C:\\Users\\fuji\\Desktop\\asztro-22-jan-14\\weboldalweboldal/static/images/hold.jpg', upload_to='blah')),
                ('leirasok', models.JSONField(blank=True, default=dict)),
                ('fokszamok', models.JSONField(blank=True, default=dict)),
                ('haz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='base.hazjegyben2')),
                ('haz_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='10+', to='base.hazjegyben2')),
                ('haz_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='11+', to='base.hazjegyben2')),
                ('haz_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='12+', to='base.hazjegyben2')),
                ('haz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='base.hazjegyben2')),
                ('haz_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='base.hazjegyben2')),
                ('haz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='base.hazjegyben2')),
                ('haz_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='base.hazjegyben2')),
                ('haz_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='base.hazjegyben2')),
                ('haz_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='base.hazjegyben2')),
                ('haz_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='base.hazjegyben2')),
                ('haz_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='base.hazjegyben2')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold+', to='base.bolygojegyben2')),
                ('jupiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiter+', to='base.bolygojegyben2')),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mars+', to='base.bolygojegyben2')),
                ('merkur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkur+', to='base.bolygojegyben2')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nap+', to='base.bolygojegyben2')),
                ('neptun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptun+', to='base.bolygojegyben2')),
                ('pluto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluto+', to='base.bolygojegyben2')),
                ('szaturnusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnusz+', to='base.bolygojegyben2')),
                ('uranusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranusz+', to='base.bolygojegyben2')),
                ('venusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venusz+', to='base.bolygojegyben2')),
            ],
        ),
        migrations.AddField(
            model_name='hazjegyben2',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy2'),
        ),
        migrations.AddField(
            model_name='bolygojegyben2',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy2'),
        ),
        migrations.CreateModel(
            name='BolygoHazban2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo2')),
                ('haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
