# Generated by Django 3.2.8 on 2021-11-10 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolygo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('tipusa', models.CharField(blank=True, max_length=20)),
                ('pontertek', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoHazban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszetett_nevID', models.CharField(max_length=30)),
                ('tulajdonsagok', models.JSONField(blank=True)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoJegyben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszetett_nevID', models.CharField(max_length=30)),
                ('altalanos_tul', models.CharField(blank=True, max_length=300)),
                ('jellemzo_erosseg', models.FloatField()),
                ('ferfi', models.CharField(blank=True, max_length=200)),
                ('no', models.CharField(blank=True, max_length=200)),
                ('gyerek', models.CharField(blank=True, max_length=200)),
                ('szulo', models.CharField(blank=True, max_length=200)),
                ('hold_erzelmek', models.CharField(blank=True, max_length=200)),
                ('hold_tehetseg', models.CharField(blank=True, max_length=200)),
                ('hold_alarendeltseg', models.CharField(blank=True, max_length=200)),
                ('hold_befogadas', models.CharField(blank=True, max_length=200)),
                ('merk_gondolkodas', models.CharField(blank=True, max_length=200)),
                ('merk_kapcsolatteremtes', models.CharField(blank=True, max_length=200)),
                ('merk_kommunkacio', models.CharField(blank=True, max_length=200)),
                ('mozgekonysag_valtoztatas', models.CharField(blank=True, max_length=200)),
                ('gyermekkora', models.CharField(blank=True, max_length=200)),
                ('tanulasa', models.CharField(blank=True, max_length=200)),
                ('elfogadasa', models.CharField(blank=True, max_length=200)),
                ('venu_anyahoz_valo_viszony', models.CharField(blank=True, max_length=200)),
                ('venu_biztonsagvagy', models.CharField(blank=True, max_length=200)),
                ('venu_stabilitas_igeny', models.CharField(blank=True, max_length=200)),
                ('venu_szepseghez_valo_viszony', models.CharField(blank=True, max_length=200)),
                ('venu_noiesseg', models.CharField(blank=True, max_length=200)),
                ('venu_szexualitas', models.CharField(blank=True, max_length=200)),
                ('venu_muveszet', models.CharField(blank=True, max_length=200)),
                ('venu_onelfogadas', models.CharField(blank=True, max_length=200)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Haz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('haztipus', models.CharField(blank=True, max_length=20)),
                ('uralkodobolygo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazJegyben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszetett_nevID', models.CharField(max_length=30)),
                ('tulajdonsagok', models.JSONField(blank=True)),
                ('haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jegy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('elem', models.CharField(blank=True, max_length=6)),
                ('minoseg', models.CharField(blank=True, max_length=10)),
                ('dekadjegy', models.CharField(blank=True, max_length=8)),
                ('paritas', models.CharField(blank=True, max_length=7)),
                ('evszak', models.CharField(blank=True, max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='KonkretHazJegyben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolygohazbanKULCS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygohazban')),
            ],
        ),
        migrations.CreateModel(
            name='KonkretBolygoJegyben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumido', models.DateTimeField()),
                ('bolygojegybenKULCS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygojegyben')),
            ],
        ),
        migrations.CreateModel(
            name='Horoszkop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.TextField(blank=True, null=True)),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('haz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='base.hazjegyben')),
                ('haz_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='10+', to='base.hazjegyben')),
                ('haz_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='11+', to='base.hazjegyben')),
                ('haz_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='12+', to='base.hazjegyben')),
                ('haz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='base.hazjegyben')),
                ('haz_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='base.hazjegyben')),
                ('haz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='base.hazjegyben')),
                ('haz_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='base.hazjegyben')),
                ('haz_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='base.hazjegyben')),
                ('haz_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='base.hazjegyben')),
                ('haz_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='base.hazjegyben')),
                ('haz_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='base.hazjegyben')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold+', to='base.bolygojegyben')),
                ('jupiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiter+', to='base.bolygojegyben')),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mars+', to='base.bolygojegyben')),
                ('merkur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkur+', to='base.bolygojegyben')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nap+', to='base.bolygojegyben')),
                ('neptun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptun+', to='base.bolygojegyben')),
                ('pluto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluto+', to='base.bolygojegyben')),
                ('szaturnusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnusz+', to='base.bolygojegyben')),
                ('uranusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranusz+', to='base.bolygojegyben')),
                ('venusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venusz+', to='base.bolygojegyben')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hazjegyben',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy'),
        ),
        migrations.AddField(
            model_name='bolygojegyben',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy'),
        ),
        migrations.AddField(
            model_name='bolygohazban',
            name='haz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz'),
        ),
    ]
