# Generated by Django 3.1 on 2022-06-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolygo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('tipus', models.CharField(blank=True, max_length=40)),
                ('pontertek', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoHazban2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoJegyben2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('adatok', models.JSONField(blank=True, default=dict)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Haz2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('tipus', models.CharField(blank=True, max_length=50)),
                ('mundan_jegye', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazJegyben2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoroszkopAdatok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonos_neve', models.CharField(max_length=30)),
                ('idopont', models.DateTimeField(default=django.utils.timezone.now)),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('neme', models.CharField(blank=True, default='', max_length=10)),
                ('kepletkep', models.ImageField(default='C:\\Users\\fuji\\Desktop\\asztro_22_6_9\\weboldalweboldal/static/images/hold.jpg', upload_to='images/')),
                ('leirasok', models.JSONField(blank=True, default=dict)),
                ('fokszamok', models.JSONField(blank=True, default=dict)),
                ('munka', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='HoroszkopAlapadat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonos_neve', models.CharField(max_length=40)),
                ('idopont', models.DateTimeField(default=django.utils.timezone.now)),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('neme', models.CharField(blank=True, default='', max_length=10)),
                ('leirasok', models.JSONField(blank=True, default=dict)),
                ('munka', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Jegy2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('leiras', models.JSONField(blank=True, default=dict, null=True)),
                ('elem', models.CharField(blank=True, max_length=20)),
                ('minoseg', models.CharField(blank=True, max_length=20)),
                ('paritas', models.CharField(blank=True, max_length=20)),
                ('evszak', models.CharField(blank=True, max_length=20)),
                ('uralkodo_bolygo', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Munkatipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munkanev', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('number_of_questions', models.IntegerField(default=1)),
                ('time', models.IntegerField(default='1', help_text='A kvíz hossza másodpercben')),
                ('valaszlehetosegek_szama', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic2')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Message2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created2', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Marks_Of_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horoszkop2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonos_neve', models.CharField(max_length=30)),
                ('idopont', models.DateTimeField(default=django.utils.timezone.now)),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('neme', models.CharField(choices=[('férfi', 'férfi'), ('nő', 'nő')], max_length=10)),
                ('kepletkep', models.ImageField(default='C:\\Users\\fuji\\Desktop\\asztro_22_6_9\\weboldalweboldal/static/images/hold.jpg', upload_to='images/')),
                ('leirasok', models.TextField(blank=True)),
                ('elemzes_adat', models.JSONField(blank=True, default=dict)),
                ('fokszamok', models.JSONField(blank=True, default=dict)),
                ('munka', models.JSONField(blank=True, default=dict)),
                ('asc_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascj', to='base.bolygojegyben2')),
                ('haz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='base.hazjegyben2')),
                ('haz_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='10+', to='base.hazjegyben2')),
                ('haz_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='11+', to='base.hazjegyben2')),
                ('haz_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='12+', to='base.hazjegyben2')),
                ('haz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='base.hazjegyben2')),
                ('haz_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='base.hazjegyben2')),
                ('haz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='base.hazjegyben2')),
                ('haz_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='base.hazjegyben2')),
                ('haz_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='base.hazjegyben2')),
                ('haz_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='base.hazjegyben2')),
                ('haz_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='base.hazjegyben2')),
                ('haz_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='base.hazjegyben2')),
                ('hold_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdh', to='base.bolygohazban2')),
                ('hold_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdj', to='base.bolygojegyben2')),
                ('jupiter_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiterh', to='base.bolygohazban2')),
                ('jupiter_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiterj', to='base.bolygojegyben2')),
                ('mars_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marsh', to='base.bolygohazban2')),
                ('mars_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marsj', to='base.bolygojegyben2')),
                ('mc_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcj', to='base.bolygojegyben2')),
                ('merkur_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkurh', to='base.bolygohazban2')),
                ('merkur_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkurj', to='base.bolygojegyben2')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='napj', to='base.bolygojegyben2')),
                ('nap_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naph', to='base.bolygohazban2')),
                ('neptun_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptunh', to='base.bolygohazban2')),
                ('neptun_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptunj', to='base.bolygojegyben2')),
                ('pluto_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plutoh', to='base.bolygohazban2')),
                ('pluto_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plutoj', to='base.bolygojegyben2')),
                ('szaturnusz_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnuszh', to='base.bolygohazban2')),
                ('szaturnusz_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnuszj', to='base.bolygojegyben2')),
                ('uranusz_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranuszh', to='base.bolygohazban2')),
                ('uranusz_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranuszj', to='base.bolygojegyben2')),
                ('venusz_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venuszh', to='base.bolygohazban2')),
                ('venusz_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venuszj', to='base.bolygojegyben2')),
            ],
        ),
        migrations.CreateModel(
            name='HazUraHazban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonsagok', models.JSONField(blank=True, default=dict, null=True)),
                ('alap_haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alap_haz', to='base.haz2')),
                ('ura_melyik_hazban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ura', to='base.haz2')),
            ],
        ),
        migrations.AddField(
            model_name='hazjegyben2',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy2'),
        ),
        migrations.AddField(
            model_name='bolygojegyben2',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy2'),
        ),
        migrations.AddField(
            model_name='bolygohazban2',
            name='haz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz2'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
            ],
        ),
    ]
