# Generated by Django 3.2.8 on 2021-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolygohazban',
            name='tulajdonsagok',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hazjegyben',
            name='tulajdonsagok',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
