# Generated by Django 3.2.12 on 2022-05-18 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroszkopAlapadat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonos_neve', models.CharField(max_length=40)),
                ('idopont', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 16, 18, 56, 20414, tzinfo=utc))),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('neme', models.CharField(blank=True, default='', max_length=10)),
                ('leirasok', models.JSONField(blank=True, default=dict)),
                ('munka', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='valaszlehetosegek_szama',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bolygo2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bolygohazban2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bolygojegyben2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='haz2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hazjegyben2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hazurahazban',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horoszkop2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horoszkop2',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 16, 18, 56, 20772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='horoszkop2',
            name='kepletkep',
            field=models.ImageField(default='/home/molnar/asztro_22_05_09weboldal/static/images/hold.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='horoszkopadatok',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horoszkopadatok',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 16, 18, 56, 19903)),
        ),
        migrations.AlterField(
            model_name='horoszkopadatok',
            name='kepletkep',
            field=models.ImageField(default='/home/molnar/asztro_22_05_09weboldal/static/images/hold.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jegy2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marks_of_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
