# Generated by Django 3.2.8 on 2021-11-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211110_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jegy',
            new_name='Jegy2',
        ),
    ]
