# Generated by Django 3.2.12 on 2022-05-28 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220518_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoszkop2',
            name='elemzes_adat',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='horoszkop2',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 3, 43, 12, 494496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='horoszkopadatok',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 3, 43, 12, 493573)),
        ),
        migrations.AlterField(
            model_name='horoszkopalapadat',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 3, 43, 12, 494138, tzinfo=utc)),
        ),
    ]
