# Generated by Django 3.2.8 on 2021-11-10 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_rename_jegy2_jegy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolygo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('tipusa', models.CharField(blank=True, max_length=20)),
                ('pontertek', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoHazban4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszetett_nevID', models.CharField(max_length=30)),
                ('tulajdonsagok', models.CharField(blank=True, max_length=200)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoJegyben4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszetett_nevID', models.CharField(max_length=30)),
                ('altalanos_tul', models.CharField(blank=True, max_length=300)),
                ('jellemzo_erosseg', models.FloatField()),
                ('ferfi', models.CharField(blank=True, max_length=200)),
                ('no', models.CharField(blank=True, max_length=200)),
                ('gyerek', models.CharField(blank=True, max_length=200)),
                ('szulo', models.CharField(blank=True, max_length=200)),
                ('hold_erzelmek', models.CharField(blank=True, max_length=200)),
                ('hold_tehetseg', models.CharField(blank=True, max_length=200)),
                ('hold_alarendeltseg', models.CharField(blank=True, max_length=200)),
                ('hold_befogadas', models.CharField(blank=True, max_length=200)),
                ('merk_gondolkodas', models.CharField(blank=True, max_length=200)),
                ('merk_kapcsolatteremtes', models.CharField(blank=True, max_length=200)),
                ('merk_kommunkacio', models.CharField(blank=True, max_length=200)),
                ('mozgekonysag_valtoztatas', models.CharField(blank=True, max_length=200)),
                ('gyermekkora', models.CharField(blank=True, max_length=200)),
                ('tanulasa', models.CharField(blank=True, max_length=200)),
                ('elfogadasa', models.CharField(blank=True, max_length=200)),
                ('venu_anyahoz_valo_viszony', models.CharField(blank=True, max_length=200)),
                ('venu_biztonsagvagy', models.CharField(blank=True, max_length=200)),
                ('venu_stabilitas_igeny', models.CharField(blank=True, max_length=200)),
                ('venu_szepseghez_valo_viszony', models.CharField(blank=True, max_length=200)),
                ('venu_noiesseg', models.CharField(blank=True, max_length=200)),
                ('venu_szexualitas', models.CharField(blank=True, max_length=200)),
                ('venu_muveszet', models.CharField(blank=True, max_length=200)),
                ('venu_onelfogadas', models.CharField(blank=True, max_length=200)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Haz4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('haztipus', models.CharField(blank=True, max_length=20)),
                ('uralkodobolygo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazJegyben4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszetett_nevID', models.CharField(max_length=30)),
                ('tulajdonsagok', models.CharField(blank=True, max_length=200)),
                ('haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horoszkop4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.TextField(blank=True, null=True)),
                ('nevID', models.CharField(max_length=30, unique=True)),
                ('haz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='base.hazjegyben4')),
                ('haz_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='10+', to='base.hazjegyben4')),
                ('haz_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='11+', to='base.hazjegyben4')),
                ('haz_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='12+', to='base.hazjegyben4')),
                ('haz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='base.hazjegyben4')),
                ('haz_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='base.hazjegyben4')),
                ('haz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='base.hazjegyben4')),
                ('haz_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='base.hazjegyben4')),
                ('haz_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='base.hazjegyben4')),
                ('haz_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='base.hazjegyben4')),
                ('haz_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='base.hazjegyben4')),
                ('haz_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='base.hazjegyben4')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold+', to='base.bolygojegyben4')),
                ('jupiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiter+', to='base.bolygojegyben4')),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mars+', to='base.bolygojegyben4')),
                ('merkur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkur+', to='base.bolygojegyben4')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nap+', to='base.bolygojegyben4')),
                ('neptun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptun+', to='base.bolygojegyben4')),
                ('pluto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluto+', to='base.bolygojegyben4')),
                ('szaturnusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnusz+', to='base.bolygojegyben4')),
                ('uranusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranusz+', to='base.bolygojegyben4')),
                ('venusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venusz+', to='base.bolygojegyben4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jegy4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('elem', models.CharField(blank=True, max_length=6)),
                ('minoseg', models.CharField(blank=True, max_length=10)),
                ('dekadjegy', models.CharField(blank=True, max_length=8)),
                ('paritas', models.CharField(blank=True, max_length=7)),
                ('evszak', models.CharField(blank=True, max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KonkretBolygoJegyben4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumido', models.DateTimeField()),
                ('bolygojegybenKULCS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygojegyben4')),
            ],
        ),
        migrations.CreateModel(
            name='KonkretHazJegyben4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolygohazbanKULCS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygohazban4')),
            ],
        ),
        migrations.CreateModel(
            name='Message4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Room4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Topic4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bolygohazban',
            name='bolygo',
        ),
        migrations.RemoveField(
            model_name='bolygohazban',
            name='haz',
        ),
        migrations.RemoveField(
            model_name='bolygojegyben',
            name='bolygo',
        ),
        migrations.RemoveField(
            model_name='bolygojegyben',
            name='jegy',
        ),
        migrations.RemoveField(
            model_name='hazjegyben',
            name='haz',
        ),
        migrations.RemoveField(
            model_name='hazjegyben',
            name='jegy',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_1',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_10',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_11',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_12',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_2',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_3',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_4',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_5',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_6',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_7',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_8',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='haz_9',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='jupiter',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='mars',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='merkur',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='nap',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='neptun',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='pluto',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='szaturnusz',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='uranusz',
        ),
        migrations.RemoveField(
            model_name='horoszkop',
            name='venusz',
        ),
        migrations.RemoveField(
            model_name='konkretbolygojegyben',
            name='bolygojegybenKULCS',
        ),
        migrations.RemoveField(
            model_name='konkrethazjegyben',
            name='bolygohazbanKULCS',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Bolygo',
        ),
        migrations.DeleteModel(
            name='BolygoHazban',
        ),
        migrations.DeleteModel(
            name='BolygoJegyben',
        ),
        migrations.DeleteModel(
            name='Haz',
        ),
        migrations.DeleteModel(
            name='HazJegyben',
        ),
        migrations.DeleteModel(
            name='Horoszkop',
        ),
        migrations.DeleteModel(
            name='Jegy',
        ),
        migrations.DeleteModel(
            name='KonkretBolygoJegyben',
        ),
        migrations.DeleteModel(
            name='KonkretHazJegyben',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='room4',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic4'),
        ),
        migrations.AddField(
            model_name='message4',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room4'),
        ),
        migrations.AddField(
            model_name='message4',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazjegyben4',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy4'),
        ),
        migrations.AddField(
            model_name='bolygojegyben4',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy4'),
        ),
        migrations.AddField(
            model_name='bolygohazban4',
            name='haz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz4'),
        ),
    ]
