# Generated by Django 3.2.8 on 2021-11-14 18:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20211110_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolygo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('tipus', models.CharField(blank=True, max_length=40)),
                ('pontertek', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoHazban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.TextField(blank=True, null=True)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolygoJegyben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.TextField(blank=True, null=True)),
                ('ferfi', models.TextField(blank=True, max_length=200, null=True)),
                ('no', models.TextField(blank=True, max_length=200, null=True)),
                ('gyerek', models.TextField(blank=True, max_length=200, null=True)),
                ('szulo', models.TextField(blank=True, max_length=200, null=True)),
                ('hold_erzelmek', models.TextField(blank=True, max_length=200, null=True)),
                ('hold_tehetseg', models.TextField(blank=True, max_length=200, null=True)),
                ('hold_alarendeltseg', models.TextField(blank=True, max_length=200, null=True)),
                ('hold_befogadas', models.TextField(blank=True, max_length=200, null=True)),
                ('merk_gondolkodas', models.TextField(blank=True, max_length=200, null=True)),
                ('merk_kapcsolatteremtes', models.TextField(blank=True, max_length=200, null=True)),
                ('merk_kommunkacio', models.TextField(blank=True, max_length=200, null=True)),
                ('mozgekonysag_valtoztatas', models.TextField(blank=True, max_length=200, null=True)),
                ('gyermekkora', models.TextField(blank=True, max_length=200, null=True)),
                ('tanulasa', models.TextField(blank=True, max_length=200, null=True)),
                ('elfogadasa', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_anyahoz_valo_viszony', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_biztonsagvagy', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_stabilitas_igeny', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_szepseghez_valo_viszony', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_noiesseg', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_szexualitas', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_muveszet', models.TextField(blank=True, max_length=200, null=True)),
                ('venu_onelfogadas', models.TextField(blank=True, max_length=200, null=True)),
                ('bolygo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bolygo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Haz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('tipus', models.CharField(blank=True, max_length=50)),
                ('mundan_jegye', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazJegyben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.TextField(blank=True, null=True)),
                ('haz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horoszkop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('tulajdonos_neve', models.CharField(max_length=30)),
                ('idopont', models.DateTimeField(default=datetime.datetime(2021, 11, 14, 19, 45, 36, 571099))),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('haz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='base.hazjegyben')),
                ('haz_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='10+', to='base.hazjegyben')),
                ('haz_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='11+', to='base.hazjegyben')),
                ('haz_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='12+', to='base.hazjegyben')),
                ('haz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='base.hazjegyben')),
                ('haz_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='base.hazjegyben')),
                ('haz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='base.hazjegyben')),
                ('haz_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='base.hazjegyben')),
                ('haz_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='base.hazjegyben')),
                ('haz_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='base.hazjegyben')),
                ('haz_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='base.hazjegyben')),
                ('haz_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='base.hazjegyben')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold+', to='base.bolygojegyben')),
                ('jupiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiter+', to='base.bolygojegyben')),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mars+', to='base.bolygojegyben')),
                ('merkur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkur+', to='base.bolygojegyben')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nap+', to='base.bolygojegyben')),
                ('neptun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptun+', to='base.bolygojegyben')),
                ('pluto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluto+', to='base.bolygojegyben')),
                ('szaturnusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnusz+', to='base.bolygojegyben')),
                ('uranusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranusz+', to='base.bolygojegyben')),
                ('venusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venusz+', to='base.bolygojegyben')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jegy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevID', models.CharField(max_length=30)),
                ('elem', models.CharField(blank=True, max_length=20)),
                ('minoseg', models.CharField(blank=True, max_length=20)),
                ('paritas', models.CharField(blank=True, max_length=20)),
                ('evszak', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bolygohazban4',
            name='bolygo',
        ),
        migrations.RemoveField(
            model_name='bolygohazban4',
            name='haz',
        ),
        migrations.RemoveField(
            model_name='bolygojegyben4',
            name='bolygo',
        ),
        migrations.RemoveField(
            model_name='bolygojegyben4',
            name='jegy',
        ),
        migrations.RemoveField(
            model_name='hazjegyben4',
            name='haz',
        ),
        migrations.RemoveField(
            model_name='hazjegyben4',
            name='jegy',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_1',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_10',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_11',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_12',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_2',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_3',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_4',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_5',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_6',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_7',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_8',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='haz_9',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='jupiter',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='mars',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='merkur',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='nap',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='neptun',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='pluto',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='szaturnusz',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='uranusz',
        ),
        migrations.RemoveField(
            model_name='horoszkop4',
            name='venusz',
        ),
        migrations.RemoveField(
            model_name='konkretbolygojegyben4',
            name='bolygojegybenKULCS',
        ),
        migrations.RemoveField(
            model_name='konkrethazjegyben4',
            name='bolygohazbanKULCS',
        ),
        migrations.RemoveField(
            model_name='message4',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message4',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room4',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room4',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room4',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Bolygo4',
        ),
        migrations.DeleteModel(
            name='BolygoHazban4',
        ),
        migrations.DeleteModel(
            name='BolygoJegyben4',
        ),
        migrations.DeleteModel(
            name='Haz4',
        ),
        migrations.DeleteModel(
            name='HazJegyben4',
        ),
        migrations.DeleteModel(
            name='Horoszkop4',
        ),
        migrations.DeleteModel(
            name='Jegy4',
        ),
        migrations.DeleteModel(
            name='KonkretBolygoJegyben4',
        ),
        migrations.DeleteModel(
            name='KonkretHazJegyben4',
        ),
        migrations.DeleteModel(
            name='Message4',
        ),
        migrations.DeleteModel(
            name='Room4',
        ),
        migrations.DeleteModel(
            name='Topic4',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazjegyben',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy'),
        ),
        migrations.AddField(
            model_name='bolygojegyben',
            name='jegy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jegy'),
        ),
        migrations.AddField(
            model_name='bolygohazban',
            name='haz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.haz'),
        ),
    ]
