# Generated by Django 3.2.8 on 2021-11-14 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211114_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoszkop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulajdonos_neve', models.CharField(max_length=30)),
                ('idopont', models.DateTimeField(default=datetime.datetime(2021, 11, 14, 19, 50, 18, 799901))),
                ('hely', models.CharField(blank=True, max_length=80)),
                ('tipus', models.CharField(blank=True, max_length=30)),
                ('haz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='base.hazjegyben')),
                ('haz_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='10+', to='base.hazjegyben')),
                ('haz_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='11+', to='base.hazjegyben')),
                ('haz_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='12+', to='base.hazjegyben')),
                ('haz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='base.hazjegyben')),
                ('haz_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='base.hazjegyben')),
                ('haz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='base.hazjegyben')),
                ('haz_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='base.hazjegyben')),
                ('haz_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='base.hazjegyben')),
                ('haz_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='base.hazjegyben')),
                ('haz_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='base.hazjegyben')),
                ('haz_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='base.hazjegyben')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold+', to='base.bolygojegyben')),
                ('jupiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiter+', to='base.bolygojegyben')),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mars+', to='base.bolygojegyben')),
                ('merkur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkur+', to='base.bolygojegyben')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nap+', to='base.bolygojegyben')),
                ('neptun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neptun+', to='base.bolygojegyben')),
                ('pluto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluto+', to='base.bolygojegyben')),
                ('szaturnusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szaturnusz+', to='base.bolygojegyben')),
                ('uranusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uranusz+', to='base.bolygojegyben')),
                ('venusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venusz+', to='base.bolygojegyben')),
            ],
        ),
        migrations.DeleteModel(
            name='Horoszkop',
        ),
    ]
