# Generated by Django 3.2.8 on 2021-11-24 16:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211114_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horoszkop1',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 17, 49, 5, 63496)),
        ),
    ]
