# Generated by Django 3.2.8 on 2021-11-24 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211124_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolygo',
            name='nevID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='haz',
            name='nevID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='horoszkop1',
            name='idopont',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 18, 23, 19, 923796)),
        ),
        migrations.AlterField(
            model_name='jegy',
            name='nevID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
