horoszkop_tarolo = [{
    "nev": "Molnár Ádám",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 8,
    "nap": 19,
    "ora": 16,
    "perc": 54,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["informatikus", "programozó"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Kapi Laura",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 6,
    "nap": 6,
    "ora": 22,
    "perc": 58,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Árpási Viktor",
    "horoszkoptipus": "radix",
    "ev": 2004,
    "honap": 4,
    "nap": 18,
    "ora": 10,
    "perc": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []

}, {
    "nev": "Wolf Levente",
    "horoszkoptipus": "radix",
    "ev": 2002,
    "honap": 3,
    "nap": 13,
    "ora": 18,
    "perc": 11,
    "hely": "Szeged",
    "kep": "",
    "munka": ["informatikus", "programozó"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Jekkel János",
    "horoszkoptipus": "radix",
    "ev": 1971,
    "honap": 9,
    "nap": 5,
    "ora": 17,
    "perc": 33,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["földműves", "biztonsági őr"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Balassa Kristóf",
    "horoszkoptipus": "radix",
    "ev": 1999,
    "honap": 8,
    "nap": 3,
    "ora": 15,
    "perc": 54,
    "hely": "Szeged",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Hápl Amíra",
    "horoszkoptipus": "radix",
    "ev": 2021,
    "honap": 11,
    "nap": 11,
    "ora": 21,
    "perc": 35,
    "hely": "Veszprém",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Kubik Anna",
    "horoszkoptipus": "radix",
    "ev": 2002,
    "honap": 12,
    "nap": 1,
    "ora": 1,
    "perc": 30,
    "hely": "Budapest",
    "kep": "",
    "munka": ["vendéglátás"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Lukács Anna",
    "horoszkoptipus": "radix",
    "ev": 1997,
    "honap": 7,
    "nap": 9,
    "ora": 13,
    "perc": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "ifj. Molnár Imre",
    "horoszkoptipus": "radix",
    "ev": 1969,
    "honap": 6,
    "nap": 5,
    "ora": 10,
    "perc": 3,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["testnevelő", "tanár"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Molnár Anna Lili",
    "horoszkoptipus": "radix",
    "ev": 2002,
    "honap": 10,
    "nap": 11,
    "ora": 11,
    "perc": 00,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Hápl Melinda",
    "horoszkoptipus": "radix",
    "ev": 1970,
    "honap": 4,
    "nap": 22,
    "ora": 3,
    "perc": 30,
    "hely": "Veszprém",
    "kep": "",
    "munka": ["ételfutár", "biztonsági őr", "festő"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "E. Bálint",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 7,
    "nap": 5,
    "ora": 9,
    "perc": 10,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Berni",
    "horoszkoptipus": "radix",
    "ev": 2002,
    "honap": 3,
    "nap": 25,
    "ora": 16,
    "perc": 31,
    "hely": "Szeged",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Ágota Bettina",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 6,
    "nap": 19,
    "ora": 18,
    "perc": 15,
    "hely": "Szolnok",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Dzseni",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 11,
    "nap": 6,
    "ora": 19,
    "perc": 40,
    "hely": "Budapest",
    "kep": "",
    "munka": ["szülésznő"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "T. Dzsoni",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 2,
    "nap": 23,
    "ora": 2,
    "perc": 25,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["testnevelő"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Emese",
    "horoszkoptipus": "radix",
    "ev": 2002,
    "honap": 4,
    "nap": 12,
    "ora": 6,
    "perc": 18,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Endi",
    "horoszkoptipus": "radix",
    "ev": 2001,
    "honap": 10,
    "nap": 28,
    "ora": 7,
    "perc": 30,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "H. Ervin",
    "horoszkoptipus": "radix",
    "ev": 1978,
    "honap": 5,
    "nap": 13,
    "ora": 21,
    "perc": 30,
    "hely": "Veszprém",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Tóth Eszter",
    "horoszkoptipus": "radix",
    "ev": 1976,
    "honap": 4,
    "nap": 4,
    "ora": 20,
    "perc": 00,
    "hely": "Budapest",
    "kep": "",
    "munka": ["tanár"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Id. Molnár Imre",
    "horoszkoptipus": "radix",
    "ev": 1944,
    "honap": 3,
    "nap": 24,
    "ora": 4,
    "perc": 14,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["műszaki szerelő"],
    "elet_leiras": [],
    "elemzes leiras": []
},
    {
        "nev": "Sallai Gabi",
        "horoszkoptipus": "radix",
        "ev": 2002,
        "honap": 5,
        "nap": 17,
        "ora": 12,
        "perc": 17,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Hajni",
        "horoszkoptipus": "radix",
        "ev": 1974,
        "honap": 10,
        "nap": 3,
        "ora": 9,
        "perc": 55,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Mihályi Ilona",
        "horoszkoptipus": "radix",
        "ev": 1959,
        "honap": 3,
        "nap": 21,
        "ora": 3,
        "perc": 3,
        "hely": "Mezőtúr",
        "kep": "",
        "munka": ["irodai alkalmazott", "cég felszámolás"],
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Balogh Kriszti",
        "horoszkoptipus": "radix",
        "ev": 2003,
        "honap": 3,
        "nap": 6,
        "ora": 18,
        "perc": 30,
        "hely": "Szolnok",
        "munka": ["fodrász", "gyári segédmunkás"]
    }, {
        "nev": "Laky Tamás",
        "horoszkoptipus": "radix",
        "ev": 2002,
        "honap": 1,
        "nap": 2,
        "ora": 16,
        "perc": 53,
        "hely": "Szolnok",
        "munka": ["állatorvos"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Orosz Léna",
        "horoszkoptipus": "radix",
        "ev": 2002,
        "honap": 4,
        "nap": 19,
        "ora": 9,
        "perc": 33,
        "hely": "Szolnok",
        "munka": ["óvónő"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Háplné Ilona",
        "horoszkoptipus": "radix",
        "ev": 1945,
        "honap": 3,
        "nap": 5,
        "ora": 6,
        "perc": 40,
        "hely": "Veszprém",
        "munka": ["festő", "porcelánfestő"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Döme Márk",
        "horoszkoptipus": "radix",
        "ev": 2001,
        "honap": 10,
        "nap": 5,
        "ora": 4,
        "perc": 42,
        "hely": "Szeged",
        "munka": ["informatikus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Lekrinczki Márti",
        "horoszkoptipus": "radix",
        "ev": 1977,
        "honap": 12,
        "nap": 20,
        "ora": 6,
        "perc": 0,
        "hely": "Veszprém",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Nagy Máté",
        "horoszkoptipus": "radix",
        "ev": 2004,
        "honap": 1,
        "nap": 6,
        "ora": 20,
        "perc": 50,
        "hely": "Szolnok",
        "munka": ["turizmus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Pojgovec Máté",
        "horoszkoptipus": "radix",
        "ev": 1999,
        "honap": 5,
        "nap": 23,
        "ora": 19,
        "perc": 30,
        "hely": "Szeged",
        "munka": ["informatikus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Nagy Ákos",
        "horoszkoptipus": "radix",
        "ev": 2000,
        "honap": 6,
        "nap": 28,
        "ora": 21,
        "perc": 36,
        "hely": "Szolnok",
        "munka": ["gépész"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Pusok Patrik",
        "horoszkoptipus": "radix",
        "ev": 2003,
        "honap": 2,
        "nap": 13,
        "ora": 9,
        "perc": 58,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Berkó Réka",
        "horoszkoptipus": "radix",
        "ev": 2005,
        "honap": 11,
        "nap": 19,
        "ora": 10,
        "perc": 44,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Kovács Viktor",
        "horoszkoptipus": "radix",
        "ev": 2001,
        "honap": 1,
        "nap": 14,
        "ora": 7,
        "perc": 32,
        "hely": "Szolnok",
        "munka": ["katona"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Molnár Szilárd",
        "horoszkoptipus": "radix",
        "ev": 2004,
        "honap": 6,
        "nap": 8,
        "ora": 8,
        "perc": 20,
        "hely": "Szolnok",
        "munka": ["katona"]
    }, {
        "nev": "Szekeres Szilvia",
        "horoszkoptipus": "radix",
        "ev": 2001,
        "honap": 6,
        "nap": 20,
        "ora": 3,
        "perc": 3,
        "hely": "Szolnok",
        "munka": ["könyvtáros"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Takács Tibor",
        "horoszkoptipus": "radix",
        "ev": 1959,
        "honap": 9,
        "nap": 5,
        "ora": 5,
        "perc": 17,
        "hely": "Szolnok",
        "munka": ["vendéglátás", "asztrológus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Tordia Tina",
        "horoszkoptipus": "radix",
        "ev": 2004,
        "honap": 6,
        "nap": 8,
        "ora": 8,
        "perc": 20,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Gulácsi Martina",
        "horoszkoptipus": "radix",
        "ev": 2005,
        "honap": 7,
        "nap": 8,
        "ora": 16,
        "perc": 44,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Toth Krisztián",
        "horoszkoptipus": "radix",
        "ev": 2001,
        "honap": 5,
        "nap": 14,
        "ora": 17,
        "perc": 6,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Zsófi",
        "horoszkoptipus": "radix",
        "ev": 2001,
        "honap": 11,
        "nap": 7,
        "ora": 10,
        "perc": 35,
        "hely": "Szolnok",
        "munka": ["régész"]
    },{
    "nev": "Kozma Kamilla",
    "horoszkoptipus": "radix",
    "ev": 2012,
    "honap": 6,
    "nap": 18,
    "ora": 14,
    "perc": 25,
    "hely": "Vác",
    "kep": "",
    "munka": [],
    "elet_leiras": ["szereti a kígyókat", "kedvenc étele a citrom és a kígyóuborka", "szeret táncolni",
                    "nem szeret házi feladatot írni", "nem szereti az érintést"],
    "elemzes leiras": []
},{
    "nev": "Kozma Korinna (Korinka)",
    "horoszkoptipus": "radix",
    "ev": 2014,
    "honap": 10,
    "nap": 1,
    "ora": 14,
    "perc": 30,
    "hely": "Vác",
    "kep": "",
    "munka": [],
    "elet_leiras": ["szeret bohóckodni és másokat megnevettetni", "teszteli a körülötte lévőket, hogy figyelnek-e rá",
                    "emaptikus, jó megérzések", "szeretne megfelelni a környezetnek, hogy legyenek barátai"],
    "elemzes leiras": []
},
{
    "nev": "Chermat Viola Viktória",
    "horoszkoptipus": "radix kb",
    "ev": 1977,
    "honap": 5,
    "nap": 29,
    "ora": 10,
    "perc": 30,
    "hely": "Vác",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}

]
