horoszkop_tarolo = [{
    "nev": "Molnár Ádám",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 2001,
    "honap": 8,
    "nap": 19,
    "ora": 16,
    "perc": 54, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["informatikus", "programozó"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Kapi Laura",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2001,
    "honap": 6,
    "nap": 6,
    "ora": 22,
    "perc": 58, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Árpási Viktor",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 2004,
    "honap": 4,
    "nap": 18,
    "ora": 17,
    "perc": 6, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []

}, {
    "nev": "Wolf Levente",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 2002,
    "honap": 3,
    "nap": 13,
    "ora": 18,
    "perc": 11, "mp": 0,
    "hely": "Szeged",
    "kep": "",
    "munka": ["informatikus", "programozó"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Jekkel János",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 1971,
    "honap": 9,
    "nap": 5,
    "ora": 17,
    "perc": 33, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["földműves", "biztonsági őr"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Balassa Kristóf",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 1999,
    "honap": 8,
    "nap": 3,
    "ora": 15,
    "perc": 54, "mp": 0,
    "hely": "Szeged",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Hápl Amíra",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2021,
    "honap": 11,
    "nap": 11,
    "ora": 21,
    "perc": 35, "mp": 0,
    "hely": "Veszprém",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Kubik Anna",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2002,
    "honap": 12,
    "nap": 1,
    "ora": 1,
    "perc": 30, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": ["vendéglátás"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Lukács Anna",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 1997,
    "honap": 7,
    "nap": 9,
    "ora": 13,
    "perc": 0, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "ifj. Molnár Imre",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 1969,
    "honap": 6,
    "nap": 5,
    "ora": 10,
    "perc": 3, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["testnevelő", "tanár"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Molnár Anna Lili",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2002,
    "honap": 10,
    "nap": 11,
    "ora": 11,
    "perc": 0, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Hápl Melinda",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 1970,
    "honap": 4,
    "nap": 22,
    "ora": 3,
    "perc": 30, "mp": 0,
    "hely": "Veszprém",
    "kep": "",
    "munka": ["ételfutár", "biztonsági őr", "festő"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "E. Bálint",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 2001,
    "honap": 7,
    "nap": 5,
    "ora": 9,
    "perc": 10, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Berni",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2002,
    "honap": 3,
    "nap": 25,
    "ora": 16,
    "perc": 31, "mp": 0,
    "hely": "Szeged",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Ágota Bettina",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2001,
    "honap": 6,
    "nap": 19,
    "ora": 18,
    "perc": 15, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Dzseni",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2001,
    "honap": 11,
    "nap": 6,
    "ora": 19,
    "perc": 40, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": ["szülésznő"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "T. Dzsoni",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 2001,
    "honap": 2,
    "nap": 23,
    "ora": 2,
    "perc": 25, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["testnevelő"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Emese",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 2002,
    "honap": 4,
    "nap": 12,
    "ora": 6,
    "perc": 18, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Endi",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 2001,
    "honap": 10,
    "nap": 28,
    "ora": 7,
    "perc": 30, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "H. Ervin",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 1978,
    "honap": 5,
    "nap": 13,
    "ora": 21,
    "perc": 30, "mp": 0,
    "hely": "Veszprém",
    "kep": "",
    "munka": [],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Tóth Eszter",
    "horoszkoptipus": "radix",
    "neme": "nő",
    "ev": 1976,
    "honap": 4,
    "nap": 4,
    "ora": 20,
    "perc": 0, "mp": 0,
    "hely": "Budapest",
    "kep": "",
    "munka": ["tanár"],
    "elet_leiras": [],
    "elemzes leiras": []
}, {
    "nev": "Id. Molnár Imre",
    "horoszkoptipus": "radix",
    "neme": "férfi",
    "ev": 1944,
    "honap": 3,
    "nap": 24,
    "ora": 4,
    "perc": 14, "mp": 0,
    "hely": "Szolnok",
    "kep": "",
    "munka": ["műszaki szerelő"],
    "elet_leiras": [],
    "elemzes leiras": []
},
    {
        "nev": "Sallai Gabi",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2002,
        "honap": 5,
        "nap": 17,
        "ora": 12,
        "perc": 17, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Hajni",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 1974,
        "honap": 10,
        "nap": 3,
        "ora": 9,
        "perc": 55, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Mihályi Ilona",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 1959,
        "honap": 3,
        "nap": 21,
        "ora": 3,
        "perc": 3, "mp": 0,
        "hely": "Mezőtúr",
        "kep": "",
        "munka": ["irodai alkalmazott", "cég felszámolás"],
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Balogh Kriszti",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2003,
        "honap": 3,
        "nap": 6,
        "ora": 18,
        "perc": 30, "mp": 0,
        "hely": "Szolnok",
        "elet_leiras": [],
        "munka": ["fodrász", "gyári segédmunkás"]
    }, {
        "nev": "Laky Tamás",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2002,
        "honap": 1,
        "nap": 2,
        "ora": 16,
        "perc": 53, "mp": 0,
        "hely": "Szolnok",
        "munka": ["állatorvos"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Orosz Léna",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2002,
        "honap": 4,
        "nap": 19,
        "ora": 9,
        "perc": 33, "mp": 0,
        "hely": "Szolnok",
        "munka": ["óvónő"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Háplné Ilona",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 1945,
        "honap": 3,
        "nap": 5,
        "ora": 6,
        "perc": 40, "mp": 0,
        "hely": "Veszprém",
        "munka": ["festő", "porcelánfestő"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Döme Márk",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2001,
        "honap": 10,
        "nap": 5,
        "ora": 4,
        "perc": 42, "mp": 0,
        "hely": "Szeged",
        "munka": ["informatikus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Lekrinczki Márti",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 1977,
        "honap": 12,
        "nap": 20,
        "ora": 6,
        "perc": 0, "mp": 0,
        "hely": "Veszprém",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Nagy Máté",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2004,
        "honap": 1,
        "nap": 6,
        "ora": 20,
        "perc": 50, "mp": 0,
        "hely": "Szolnok",
        "munka": ["turizmus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Pojgovec Máté",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 1999,
        "honap": 5,
        "nap": 23,
        "ora": 19,
        "perc": 30, "mp": 0,
        "hely": "Szeged",
        "munka": ["informatikus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Nagy Ákos",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2000,
        "honap": 6,
        "nap": 28,
        "ora": 21,
        "perc": 36, "mp": 0,
        "hely": "Szolnok",
        "munka": ["gépész"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Pusok Patrik",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2003,
        "honap": 2,
        "nap": 13,
        "ora": 9,
        "perc": 58, "mp": 0,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Berkó Réka",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2005,
        "honap": 11,
        "nap": 19,
        "ora": 10,
        "perc": 44, "mp": 0,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Kovács Viktor",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2001,
        "honap": 1,
        "nap": 14,
        "ora": 7,
        "perc": 32, "mp": 0,
        "hely": "Szolnok",
        "munka": ["katona"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Molnár Szilárd",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2004,
        "honap": 6,
        "nap": 8,
        "ora": 8,
        "perc": 20, "mp": 0,
        "hely": "Szolnok",
        "munka": ["katona"],
        "elet_leiras": []
    }, {
        "nev": "Szekeres Szilvia",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2001,
        "honap": 6,
        "nap": 20,
        "ora": 3,
        "perc": 3, "mp": 0,
        "hely": "Szolnok",
        "munka": ["könyvtáros"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Takács Tibor",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 1959,
        "honap": 9,
        "nap": 5,
        "ora": 5,
        "perc": 17, "mp": 0,
        "hely": "Szolnok",
        "munka": ["vendéglátás", "asztrológus"],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Tordia Tina",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2004,
        "honap": 6,
        "nap": 8,
        "ora": 8,
        "perc": 20, "mp": 0,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Gulácsi Martina",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2005,
        "honap": 7,
        "nap": 8,
        "ora": 16,
        "perc": 44, "mp": 0,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Toth Krisztián",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 2001,
        "honap": 5,
        "nap": 14,
        "ora": 17,
        "perc": 6, "mp": 0,
        "hely": "Szolnok",
        "munka": [],
        "kep": "",
        "elet_leiras": [],
        "elemzes leiras": []
    }, {
        "nev": "Zsófi",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2001,
        "honap": 11,
        "nap": 7,
        "ora": 10,
        "perc": 35, "mp": 0,
        "hely": "Szolnok","elet_leiras": [],
        "munka": ["régész"]
    }, {
        "nev": "Kozma Kamilla",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2012,
        "honap": 6,
        "nap": 18,
        "ora": 14,
        "perc": 25, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": ["szereti a kígyókat", "kedvenc étele a citrom és a kígyóuborka", "szeret táncolni",
                        "nem szeret házi feladatot írni", "nem szereti az érintést"],
        "elemzes leiras": []
    }, {
        "nev": "Kozma Korinna (Korinka)",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2014,
        "honap": 10,
        "nap": 1,
        "ora": 14,
        "perc": 30, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": ["szeret bohóckodni és másokat megnevettetni",
                        "teszteli a körülötte lévőket, hogy figyelnek-e rá",
                        "emaptikus, jó megérzések", "szeretne megfelelni a környezetnek, hogy legyenek barátai"],
        "elemzes leiras": []
    },
    {
        "nev": "Chermat Viola Viktória",
        "horoszkoptipus": "radix kb",
        "neme": "nő",
        "ev": 1977,
        "honap": 5,
        "nap": 29,
        "ora": 10,
        "perc": 30, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": ["szépségszalon"],
        "elet_leiras": [],
        "elemzes leiras": []
    },
    {
        "nev": "Kapi Lilla",
        "horoszkoptipus": "radix",
        "neme": "nő",
        "ev": 2004,
        "honap": 3,
        "nap": 16,
        "ora": 10,
        "perc": 50, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
    },
    {
        "nev": "Kapi Levente",
        "horoszkoptipus": "radix",
        "neme": "férfi",
        "ev": 1998,
        "honap": 12,
        "nap": 20,
        "ora": 14,
        "perc": 25, "mp": 0,
        "hely": "Vác",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
    },
    {
        "nev": "Judit",
        "horoszkoptipus": "radix kb",
        "neme": "nő",
        "ev": 1998,
        "honap": 12,
        "nap": 20,
        "ora": 14,
        "perc": 25, "mp": 0,
        "hely": "Budapest",
        "kep": "",
        "munka": [],
        "elet_leiras": [],
        "elemzes leiras": []
                   },
    {
        "nev": "Órai_anyag_2_3_Rózsa",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1996,
        "honap": 9,
        "nap": 12,
        "ora": 12,
        "perc": 10, "mp": 0,
        "hely": "Győr",
        "kep": "",
        "munka": [""],
        "elet_leiras": ["általános iskola kitűnő",
                        "szépség szakma",
                        "fotózási ajánlatokat kap",
                        "pszichológia érdekli"
                        ],
        "elemzes leiras": ["a tudat nem képes összehozni a szépségipart a psichológiával"
                           "Mert nem tudna hiteles lenni. Pl nem tudna segíteni egy önbizalomhiányos paciensnek, mert őmaga nagyon szép"
                           ]
    }, {
        "nev": "Órai_anyag_2_4_Károly",
        "horoszkoptipus": "radix", "neme": "férfi",
        "ev": 1949,
        "honap": 11,
        "nap": 25,
        "ora": 17,
        "perc": 25,
        "mp": 0,
        "hely": "Győr",
        "kep": "",
        "munka": [],
        "elet_leiras": [
            "van 3 gyereke 1. felségtől 2 , második felségtől 2",
            "rendszerváltásban meggazdagodott"
        ],
        "elemzes leiras": [
        ],

    }, {
        "nev": "Órai_anyag_2_5_Lilla",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1985,
        "honap": 10,
        "nap": 17,
        "ora": 13,
        "perc": 30,
        "mp": 0,
        "hely": "Tatabánya",
        "kep": "",
        "munka": ["jog"],
        "elet_leiras": [
            "színiskolába jár"
        ],
        "elemzes leiras": [
            "Lilla név nap szerű név",
            ""
        ]
    }, {
        "nev": "Órai_anyag_2_10_Ilona",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1964,
        "honap": 12,
        "nap": 21,
        "ora": 4,
        "perc": 30, "mp": 0,
        "hely": "Békéscsaba",
        "kep": "",
        "munka": ["zenész"],
        "elet_leiras": [
            "egyedül neveli kislányát",
            "elvált",
            "báttya korán meghalt veserákban",
            "erős aszmája van",
            "fuvolázik"
        ],
        "elemzes leiras": [
        ]
    }, {
        "nev": "Órai_anyag_2_11",
        "horoszkoptipus": "radix", "neme": "férfi",
        "ev": 1975,
        "honap": 3,
        "nap": 10,
        "ora": 16,
        "perc": 45,"mp": 0,
        "hely": "Győr",
        "kep": "",
        "munka": ["zenész"],
        "elet_leiras": [
            "egyedül neveli kislányát",
            "elvált",
            "báttya korán meghalt veserákban",
            "erős aszmája van",
            "fuvolázik"
        ],
        "elemzes leiras": [
        ]
    }, {
        "nev": "Órai_anyag_2_12???",
        "horoszkoptipus": "radix",
        "ev": 1975,
        "honap": 3,
        "nap": 10,
        "ora": 16,
        "perc": 45,"mp": 0,
        "hely": "Győr",
        "kep": "", "neme": "nő",
        "munka": ["fodrász"],
        "elet_leiras": [
            "egyedül neveli egyerekét",
            "szeretői kapcsolatba került egy "
        ],
        "elemzes leiras": [
        ]
    }, {
        "nev": "Órai_anyag_2_10_Ilona",
        "horoszkoptipus": "radix", "neme": "férfi",
        "ev": 1964, "honap": 12, "nap": 21, "ora": 4, "perc": 30, "mp": 0,
        "hely": "Békéscsaba", "kep": "",
        "munka": ["Zenéz?"],
        "elet_leiras": ["egyedül neveli kislányát elvált",
                        "kislánya egy házasság utáni kapcsolatból van(akivel szakítottak)",
                        "báttya meghalt veserákban",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_12??",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1988, "honap": 11, "nap": 1, "ora": 7, "perc": 30, "mp": 0,
        "hely": "Veszprém", "kep": "",
        "munka": ["jogi asszisztens", "nemzetközi tanulmányok"],
        "elet_leiras": ["a pasik nem működnek neki ",
                        "sok helyen dolgozik, hogy legyen pénzze",

                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_17_Melinda",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1977, "honap": 12, "nap": 22, "ora": 23, "perc": 2, "mp": 0,
        "hely": "Győr", "kep": "",
        "munka": ["audi kommunikációs osztáy"],
        "elet_leiras": ["férjnél van",
                        "gyerek nem akar megfoganni",
                        "",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_19_Izabella",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1994, "honap": 11, "nap": 1, "ora": 7, "perc": 30, "mp": 0,
        "hely": "Mosonmagyaróvár", "kep": "",
        "munka": ["kórházban laborban"],
        "elet_leiras": ["19 évesen idősebb férfihez ment és váltak",
                        "",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_19_Rebeka??",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1994, "honap": 2, "nap": 23, "ora": 11, "perc": 45, "mp": 0,
        "hely": "Győr", "kep": "",
        "munka": [],
        "elet_leiras": [
        ],
        "elemzes leiras": []
    },
    {
        "nev": "Órai_anyag_2_20_Erzsébet",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1962, "honap": 6, "nap": 24, "ora": 0, "perc": 30, "mp": 0,
        "hely": "Eger", "kep": "",
        "munka": ["?"],
        "elet_leiras": ["",
                        "",
                        "",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_22_Vera",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1979, "honap": 2, "nap": 26, "ora": 12, "perc": 5, "mp": 0,
        "hely": "Salgótarján", "kep": "",
        "munka": ["?"],
        "elet_leiras": ["",
                        "",
                        "",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_23_Zsófia",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1989, "honap": 4, "nap": 24, "ora": 17, "perc": 34, "mp": 0,
        "hely": "Budapest", "kep": "",
        "munka": ["?"],
        "elet_leiras": ["",
                        "",
                        "",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_24_József",
        "horoszkoptipus": "radix", "neme": "férfi",
        "ev": 1966, "honap": 6, "nap": 8, "ora": 5, "perc": 37, "mp": 0,
        "hely": "Győr", "kep": "",
        "munka": ["?"],
        "elet_leiras": [
        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_25_Éva",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1994, "honap": 6, "nap": 4, "ora": 9, "perc": 30, "mp": 0,
        "hely": "Sopron", "kep": "",
        "munka": ["?"],
        "elet_leiras": ["",
                        "",
                        "",
                        ""
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_26_Bea",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1974,
        "honap": 1,
        "nap": 9,
        "ora": 21,
        "perc": 15,
        "hely": "Győr",
        "kep": "",
        "munka": ["titkárnő"],
        "elet_leiras": [
        ],
        "elemzes leiras": [
        ]
    }, {
        "nev": "Órai_anyag_2_27_Anna",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1963, "honap": 1, "nap": 16, "ora": 5, "perc": 30, "mp": 0,
        "hely": "Mosonmagyaróvár", "kep": "",
        "munka": ["zongorista kísérő"],
        "elet_leiras": ["nincs férjnél nem is volt",
                        "nincs gyereke",
                        "rossz párkapcsolatokon ment keresztül",
                        "bőrproblémák"
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_28_János",
        "horoszkoptipus": "radix", "neme": "férfi",
        "ev": 1988, "honap": 4, "nap": 22, "ora": 9, "perc": 30, "mp": 0,
        "hely": "Mosonmagyaróvár", "kep": "",
        "munka": ["?"],
        "elet_leiras": ["",
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_29_Krisztina",
        "horoszkoptipus": "radix", "neme": "nő",
        "ev": 1968, "honap": 7, "nap": 16, "ora": 12, "perc": 0, "mp": 0,

        "hely": "Mosonmagyaróvár", "kep": "",
        "munka": ["építőipar"],
        "elet_leiras": ["vállalkozás férjével, anyagilag sok tartozás",
                        "2 lánygyermek",
                        "elvált",
                        "nagylánya hozzá költözött",
                        "idegösszeomlás, gyógyszerezés",
                        "iszik(alkoholizál)"
                        ],
        "elemzes leiras": []
    }, {
        "nev": "Órai_anyag_2_30_Balázs",
        "horoszkoptipus": "radix", "neme": "férfi",
        "ev": 1977, "honap": 10, "nap": 15, "ora": 11, "perc": 30, "mp": 0,
        "hely": "Mosonmagyaróvár", "kep": "",
        "munka": ["autószerelő"],
        "elet_leiras": ["nehezen jött össze az első gyerek",
                        "2 gyerek született",
                        "nagy ház nagy autó, nagy csónak",
                        "cukorbeteg 13 éves kora óta",
                        "sok baleset, sok műtét"
                        ],
        "elemzes leiras": []
    }
]
